-- Simulation/edge telemetry for the Franka portfolio project.
-- Apply with the Supabase SQL editor or psql as a database owner.

create table if not exists public.franka_telemetry (
  id bigint generated by default as identity primary key,
  run_id uuid not null,
  source text not null,
  event_type text not null check (
    event_type in ('safety_decision', 'estop_trigger', 'estop_clear', 'node_heartbeat')
  ),
  observed_at timestamptz not null,
  safety_reason text,
  accepted boolean,
  latency_ms double precision check (latency_ms is null or latency_ms >= 0),
  value double precision,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists franka_telemetry_run_time_idx
  on public.franka_telemetry (run_id, observed_at desc);

create index if not exists franka_telemetry_event_time_idx
  on public.franka_telemetry (event_type, observed_at desc);

alter table public.franka_telemetry enable row level security;

-- Deliberately create no anon/authenticated policies. The MVP writer uses a key
-- injected only on a trusted edge host. For production, replace direct service-role
-- writes with an authenticated edge function or a dedicated least-privilege role.

-- Verification query:
-- select event_type, safety_reason, accepted, latency_ms, observed_at
-- from public.franka_telemetry
-- order by observed_at desc
-- limit 20;
